version: '3.8'
services:
  task-postgres:
    image: postgres:latest
    container_name: task-postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - task-postgres:/var/lib/postgresql/data

  task-redis:
    image: redis:latest
    container_name: task-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - task-redis:/var/lib/redis/data

volumes:
  task-postgres:
    name: postgres-db
  task-redis:
    name: redis-db
